### ISSUE TITLE
testbed shows failures

### ISSUE THREAD

**Issue by gliptak** [nick8325/quickcheck#109]
When running with Git HEAD:

```
QuickCheck-2.9.1: test (suite: test-quickcheck)

=== prop_ToSortedList from examples/Heap.hs:123 ===
*** Failed! Falsifiable (after 7 tests):  
Node (-4) (Node 4 (Node 7 Empty Empty) (Node 8 Empty Empty)) (Node (-2) (Node 5 Empty Empty) (Node (-1) Empty Empty))

QuickCheck-2.9.1: test (suite: test-quickcheck-gcoarbitrary)

*** Failed! Falsifiable (after 4 tests and 4 shrinks):    
{_->2}
```

**Comment by nick8325** [comment]
Right, this is an example of a false property. Note that `cabal test` considers the test suite to have passed, as we never return a failing exit code.

Really, we should check the test results properly (and perhaps use `expectFailure` for the false property above) rather than relying on me to read the output.

**Comment by nick8325** [comment]
Fixed!
