### ISSUE TITLE
Decouple Arbitrary from QuickCheck

### ISSUE THREAD

**Issue by kvanberendonck** [nick8325/quickcheck#158]
So that I can ship libraries with Arbitrary instances without adding QuickCheck (and hence all its dependencies) as a library dependency.

**Comment by RyanGlScott** [comment]
_All_ its dependencies? You make it sound like there's an enormous amount of them, when really `QuickCheck`'s dependencies are quite svelte by Haskell standards. With GHC 8.0, you only need `primitive`, `random`, and `tf-random`, which is quite reasonble IMHO.

**Comment by kvanberendonck** [comment]
It just seems a little unreasonable (and this is opinionated) to have 'QuickCheck' as a dependency for a library if you want to offer 'QuickCheck' support for a couple of users who might find it useful in their unit testing.

**Comment by kvanberendonck** [comment]
If there was a standalone lightweight `arbitrary` package, you could just merge all the *-instances packages directly into their actual packages. Additionally, it works around a problem with stack/cabal where the dependency system means you can't have tests that depend on benchmarks or vice-verca and if you want to decouple your arbitrary instances from your unit tests without pulling in QuickCheck as a dependency in your main app/lib whilst still allowing maximum access you have to make a separate utility library (otherwise circular reference).

**Comment by RyanGlScott** [comment]
...but depending on slightly modified version of `QuickCheck` that only exports `Arbitrary` _is_ reasonable? I'm not trying to be snarky here, I genuinely don't understand the reasoning. I think including `QuickCheck` as a library dependency is quite reasonable.

**Comment by kvanberendonck** [comment]
OK maybe my suggestion was unreasonable. Do you mind leaving it open to gather some more data?

**Comment by kvanberendonck** [comment]
The way I imagined this would work is making a new library `Data.Arbitrary` and having `QuickCheck.Arbitrary` simply re-export from there so that new versions of `QuickCheck` allow people to import `Data.Arbitrary` for other purposes.

**Comment by sol** [comment]
I would like to see this too.  Ideally even going one step further and splitting `QuickCheck` into two packages e.g. `QuickCheck-core` and `QuickCheck`.  `QuickCheck-core` would provide everything we need to

1. Run QuickCheck properties
2. Extend QuickCheck

with minimal dependencies.

`QuickCheck` on the other hand would depend on `QuickCheck-core` and provide all the additional instances that we currently have.

**Comment by thumphries** [comment]
A common way around this problem is to distribute `my-library-test` along with `my-library`, where `my-library-test` contains orphan `Arbitrary` instances. This isn't great, and maybe a change to QuickCheck is the way to avoid the orphans.

You can also get a long way by avoiding `Arbitrary` entirely. Bundle `arbitraryFoo :: Gen Foo` in `my-library-test`, which can then be -Wall clean. Users no longer depend on your version of QuickCheck.

> I think including QuickCheck as a library dependency is quite reasonable.

dependency clashes based on unnecessary QuickCheck constraints are not much fun 😅

**Comment by phadej** [comment]
`arbitraryFoo :: Gen Foo` loses the selling point of quickcheck: Shrinking.

@sol: @kvanberendonck wants it the other way around, all instances in *core* package, but the driver code in another one.

I agree with @RyanGlScott: `QuickCheck` has quite minimal dependencies, the [`quickcheck-instances`](http://hackage.haskell.org/package/quickcheck-instances) provides more instances, for packages QuickCheck don't depend upon, or which aren't fused into `base`. But it's quite light too, as `quickcheck-instances` depends only on packages in the Haskell Platform.

Not depending on e.g. `semigroups` or `nats` to shim instances is IMHO bad idea, I very dislike `light` flag (luckily I don't have to use *or* maintain it). In practice you can very effectively cache those dependencies on travis, so the build time argument isn't valid. The way better argument,
is to make `QuickCheck` compiable with other compilers than GHC, and that I'd respect.

As a contributor to `quickcheck-instances` I really wanted to have everything shimmed already in
`QuickCheck`, because having proper guards in `quickcheck-instances`, based on both `base` and `QuickCheck` is/was a mess.

I'd also would like to remove
> Since all of these instances are provided as orphans, I recommend that you do not use this library within another library module, so that you don't impose these instances on down-stream consumers of your code.

disclaimer from `quickcheck-instance` description, but that probably requires quite a lot of work. E.g. `aeson` couldn't provide `Arbitrary` instances, without copying the definitions for `Vector`, `Scientific` and `HashMap` (though completely arbitrary `Value` isn't that useful).

Edward Kmett has per-package flags in some of his packages, e.g. in [`contravariant`](http://hackage.haskell.org/package/contravariant) and has better worded description&disclaimer (emphasis by me):

> You can disable the use of the `tagged` package using `-f-tagged`. Disabling this is an **unsupported configuration**, but it may be useful for accelerating builds in sandboxes **for expert users**.

And you actually have to consistently use `-f-tagged` across dependencies, to really have the benefit. I'm not sure, you'll actually save that much wall clock time. Both `stack` and `cabal new-build` diminish the need, as they do good job in caching dependencies.

**Comment by thumphries** [comment]
> `arbitraryFoo :: Gen Foo` loses the selling point of quickcheck: Shrinking.

Shrinking is available via `forAllShrink` if you also provide `shrinkFoo :: (Foo -> [Foo])`.

Recreating the typeclass elsewhere will recreate the 'dependency vs orphan' decision for users. You can avoid this decision entirely by giving your generators names and putting them in a separate package.

**Comment by nick8325** [comment]
I like @sol's idea of splitting QuickCheck into two packages, one called say `QuickCheck-light` which provides as much as possible while keeping the dependencies light, and then `QuickCheck` which adds all the instances that require shims.

QuickCheck has few dependencies on new GHC versions but on older versions there has been a lot of dependency bloat.

Here is what gets installed when you build QuickCheck on GHC 8.0: `primitive`, `random`, `tf-random`. (By the way, all these are needed for `Arbitrary`, so splitting that out into its own package wouldn't help here.)

And here is what you get on GHC 7.6: `bytestring-builder`, `random`, `text`, `hashable`, `nats`, `transformers`, `primitive`, `tf-random`, `transformers-compat`, `tagged`, `unordered-containers`, `semigroups`.

I sort of assumed that this only causes longer compile times, but it seems it can break packages too. If you're writing a library and want to define an `Arbitrary` instance, you suddenly get a load of extra dependencies like `text`, and as @thumphries said, maybe your user needs a different version of `text` and now they can't use your library. This seems really bad. If we split QuickCheck into two packages, then library authors can just depend on `QuickCheck-light` and all should be well.

**Comment by kvanberendonck** [comment]
Personally I don't like the two package option, as when providing instances I'd rather provide modular instances than instances specific to QuickCheck (other testing frameworks in 5 years could use arbitrary for example..)

**Comment by nick8325** [comment]
But I don't really get it - if we make sure that there is a version of QuickCheck available with few dependencies, then can't other testing frameworks use arbitrary anyway? What would the difference be between depending on `QuickCheck-light` and depending on `arbitrary`?

**Comment by nick8325** [comment]
I've just tried splitting QuickCheck up into two packages (see https://github.com/nick8325/quickcheck/tree/light) but it's not as nice as I'd hoped.

I was hoping to have the following module layout:

* `QuickCheck-light` contains all modules that are currently in `QuickCheck`, except that the main `Test.QuickCheck` module is renamed to `Test.QuickCheck.Light` and the problematic instances are removed.
* `QuickCheck` contains only one module, `Test.QuickCheck`, which re-exports `Test.QuickCheck.Light` as well as the extra instances.

But that doesn't work because of two problems:

* The Haddock documentation for `Test.QuickCheck` would just contain a link to `Test.QuickCheck.Light` instead of including the actual documentation.
* Any package which imports e.g. `Test.QuickCheck.Arbitrary` would now need to depend directly on `QuickCheck-light`; depending on `QuickCheck` wouldn't work. The Cabal stanza `reexported-modules` is supposed to fix this but unfortunately it only works from GHC 7.10 upwards.

So instead I have done it as follows, with a bit of shell scripting to make it less unpleasant to keep up to date:

* `QuickCheck-light` contains all QuickCheck modules, but renamed to be under the `Test.QuickCheck.Light.*` namespace.
* `QuickCheck` re-exports all of `QuickCheck-light`'s modules, renaming them to be under `Test.QuickCheck.*` and re-exporting the functions individually to fix the Haddock documentation.

But it's not very nice. Comments? Any ideas for a better design welcome!

**Comment by phadej** [comment]
FWIW, it seems that discussion on this, and trying to find the solution have took at least the same magnitude of *human time*, then we can save the build time from *machines*. I'm even more strongly :-1: to making maintaining or/an depending on `QuickCheck` more complicated.

**Comment by kvanberendonck** [comment]
I don't think build times were every a primary reason for it, but rather versioning. I still think that it would be better from a library POV to export the Arbitrary primitive as a minimal package (in the same way tagged and reflection do).

**Comment by phadej** [comment]
@kvanberendonck I disagree, `QuickCheck` has quite stable API, breaking changes are introduced once a year. And if you read thru the changelog; they aren't even that major (i.e. don't break everyone's code):
- `2.6` in 2013-03-17
- `2.7` in 2014-03-19
- `2.8` in 2015-03-18
- `2.9` in 2016-07-10

Trying to have longer stability guarantees is IMHO wasted effort.

**Comment by nick8325** [comment]
For me it's (mostly) not about reducing build times but preventing build failures. If a library author wants to include an `Arbitrary` instance with their package, they currently bring in a load of extra dependencies that potentially break installation for their end users. It would be really nice if we could avoid creating that problem.

Here is another thing that really seems like a design smell to me: with the current set of dependencies, neither QuickCheck nor `text` are able to define an `Arbitrary Text` instance! Since we don't want to add an unconditional `text` dependency to QuickCheck, we can't define one here; but `text` can't define one because it will create a circular dependency on older GHCs.

But doing the split came out much more complicated than I hoped. I'm not keen on adding a big maintenance burden.

What if we moved the problematic instances into `quickcheck-instances`? We could say that QuickCheck will continue to have a minimal set of dependencies, but that the instances in `quickcheck-instances` are considered "official" and users shouldn't define their own versions of them. Would that solve the problem with orphan instances?

**Comment by phadej** [comment]
The build failure due failing-to-build dependencies should never happen :tm: Hackage Trustees will and do help and advice package authors to have correct bounds / metadata specifications so `cabal` could do it's job well (i.e. not try to build plans which are known to be non-buildable). `QuickCheck` has very small dependency footprint, I doubt there is evidence that bringing QuickCheck into the build plan would make it invalid. After all, majority of libraries have `QuickCheck` dependency in their test-suites, and those seem to build ok.

About moving instances: I'm not against **unconditionally** moving e.g. `NonEmpty` instances to `quickcheck-instances`, but having the instance sometimes defined in `QuickCheck` and sometimes in `quickcheck-instances` is a maintenance burden (as you'll need to duplicate code and keep it synced), also to downstream users.

cc @hvr

**Comment by phadej** [comment]
One more thing: to meaningfully write instances one needs enough building-blocks to write those instances. For me that building block is often `quickcheck-instances`, so my problem, is that if I want to export `Arbitrary` instance for my type from the library, I need to either
- depend on `quickcheck-instances` to get building-blocks
- or copy&paste code

Neither option is very great. I'd rather have as many building blocks possible in `QuickCheck` directly. E.g. there are very little practical reasons for `QuickCheck` not to depend on `text`, `time` or `vector`. It's a good question whether `Arbitrary Vector` should be in `vector` or `QuickCheck`. The same problem is with `Binary`, where I collected enough instances to [`binary-orphans`](http://hackage.haskell.org/package/binary-orphans)

**Comment by kvanberendonck** [comment]
That's not that difficult, you can provide all the Prelude types in arbitrary, then all the other types in -instances packages , which QuickCheck can reexport for compatibility.

**Comment by nick8325** [comment]
I don't agree that the dependency footprint is small when packages like `text` are included. I would say QuickCheck has few dependencies on the latest GHC but very many more on older versions. I would rather avoid adding all those dependencies unconditionally.

I agree that any move must be unconditional, it would be crazy to require users to depend on different packages depending on their GHC version.

I see that using `quickcheck-instances` causes problems now, but I wonder if we can solve that by officially recommending that people use it, and that the instances in there shouldn't be considered orphan instances.

**Comment by phadej** [comment]
@nick8325 I'm ok with moving `nats`, `semigroups`, `tagged` (and if there are others) instances to `quickcheck-instances`. I'm not a maintainer of it though, so it has to be co-ordinated with @aslatter (unfortunately he's not very active). For the record, I offered to be a co-maintainer of `quickcheck-instances`, but never got a response (hopefully they didn't go to spam).

**Comment by nick8325** [comment]
Right, we should of course check with @aslatter. @aslatter, is it ok if we move some instances from the main QuickCheck package to `quickcheck-instances`? It would probably need to be released in sync (ish) with the next version of QuickCheck.

**Comment by phadej** [comment]
I requested a package takeover: https://mail.haskell.org/pipermail/haskell-cafe/2017-April/126726.html

If the package will be handed to me, I don't feel uneasy to migrate the instances; after all that would still be in the very scope of `quickcheck-instances`:

> The goal is to supply QuickCheck instances for types provided by the Haskell Platform.

**Comment by nick8325** [comment]
Unfortunate that there's been no reply to your email. I think it's high time to release a new QuickCheck version, but I would like to get this sorted out first.

I suppose we could release a new package of extra instances ourselves (`quickcheck-base-instances`? `quickcheck-extra-instances`?) It may be confusing to have a proliferation of instances packages though, and would probably cause trouble if they got merged into `quickcheck-instances` in the future. Any thoughts?

**Comment by phadej** [comment]
@nick8325, I'd ping other Hackage Trustees with issue; let's sort it out this week.

**Comment by phadej** [comment]
@nick8325 I got the upload rights for `quickcheck-instances`; so we can proceed with this.

Should I do a PR stripping off non-`base` dependencies (and migrating the instances to `quickcheck-instances`)?

**Comment by nick8325** [comment]
Great! Yes, please do. The new version of QuickCheck will be 2.10 if you want to make the instances in `quickcheck-instances` conditional.

BTW, I ran into a couple of other problems when I tried to install `quickcheck-instances`: the array instances are now in `QuickCheck` itself (since we depend on `array` via `containers`), so there is a duplicate instance, and also it pulls in an old version of `time` (version 1.8.0.1 is the latest).

**Comment by RyanGlScott** [comment]
How is this going, @phadej?

**Comment by phadej** [comment]
Going to look into this later today & tomorrow

**Comment by phadej** [comment]
@nick8325 I'll remove the `Array` instances from `QuickCheck`, and overall all dependencies `QuickCheck` doesn't need to depend upon.

**Comment by nick8325** [comment]
Closing as #166 made QuickCheck very dependency-light again.
