### ISSUE TITLE
Include counterexample in Result

### ISSUE THREAD

**Issue by sol** [nick8325/quickcheck#174]
Given a property `prop` with
```haskell
import Test.QuickCheck
import qualified Test.QuickCheck.Property as Property

prop :: Int -> Int -> Property.Result
prop n m = Property.failed { Property.reason = unlines ["some", "failure", "reason"] }
```
when we run it, we get the following output:
```
ghci> r <- quickCheckResult prop
*** Failed! (after 1 test):                      
some
failure
reason
0
0
```

This output is composed of a generic `** Failed!` message, the number of tests and shrinks, the failure reason and zero or more counterexamples.

We have access to most of this information through the result type, e.g.:

```
ghci> numTests r
1
ghci> numShrinks r
0
ghci> reason r
"some\nfailure\nreason\n"
```
But getting hold of the counterexamples, while possible, is not straight forward.

@nick8325 Looking at the code, it's not trivial to add this functionality.  I'm puzzled whether `IO`-callbacks are the right design choice for implementing `counterexample` in the first place.  Functionally, we would just need to collect them in some list, so that we can deal with them how ever we see fit *after* evaluating the property. Any thoughts?

While I'm already in rant-mode, would you accept a patch that makes the `Result`-type total?  And how about adding proper unit tests (e.g. using my zero-dependency [`nanospec`](https://hackage.haskell.org/package/nanospec))?

**Comment by sol** [comment]
> But getting hold of the counterexamples, while possible, is not straight forward.

Just to clarify what I mean with "possible".  As we have all the other information that composes the `output`, we can construct a `prefix` so that:

```
prefix + counterexamples == output
```
or in other words:

```haskell
Just counterexample = stripPrefix prefix output
```

**Comment by sol** [comment]
> `Just counterexamples = stripPrefix prefix output`

But even with this approach, we have no way see how many counterexamples there were or separate them into individual chunks (one counterexample per line is common, but I assume it's not enforced, right?).

**Comment by phadej** [comment]
@sol to clarify, is it enough for you to get a `[String]` of counterexamples? Because embedding an actual types is difficult (though possible thru `Dynamic`)

**Comment by nick8325** [comment]
Yep, that would be a useful feature. A `[String]` rather than a `String` would be better, so that the user can use `read` to get the counterexample as a Haskell value.

> @nick8325 Looking at the code, it's not trivial to add this functionality. I'm puzzled whether IO-callbacks are the right design choice for implementing counterexample in the first place. Functionally, we would just need to collect them in some list, so that we can deal with them how ever we see fit after evaluating the property. Any thoughts?

Some people use `whenFail (putStrLn ...)` to print counterexamples (since `counterexample` hasn't always existed), so the output of `counterexample` and `whenFail` needs to be interleaved.

Anyway, I suppose it shouldn't be so hard to collect a list of strings as well as printing them out. The main constraint is that it shouldn't bother evaluating the strings unless there is a test case failure (but probably the conversion from `Property.Result` to `Test.Result` can handle that).

I'll see if I can have a go at adding it.

> While I'm already in rant-mode, would you accept a patch that makes the Result-type total?

Yes! I didn't know it wasn't total.

> And how about adding proper unit tests (e.g. using my zero-dependency nanospec)?

All tests welcome! I never get around to adding them myself...
