### ISSUE TITLE
Applicative and Monad instances don't deal with size.

### ISSUE THREAD

**Issue by NorfairKing** [nick8325/quickcheck#198]
To make the size work correctly, the Applicative and Monad instance should split the allocated size up and partition it accross the two parts of the generator.

The size of `(,) <$> arbitrary <*> arbitrary) is currently twice the size of `arbitrary` while it should be the same size.

**Comment by Lysxia** [comment]
What makes the current behavior incorrect? I think the "size" parameter is just a convenience for those writing generators to easily guarantee termination, and it's fine not to use it when it is not appropriate. Furthermore, the naive way to split it wouldn't satisfy the monad laws; is there a more satisfactory solution?

**Comment by NorfairKing** [comment]
"it's fine not to use it when it is not appropriate." -> This is dangerous with respect to memory explosions.
Try generating a `[[[[[[[Int]]]]]]]` of size `10` to see what I mean.
Could you elaborate on the problem with the monad laws please?

**Comment by Lysxia** [comment]
It is true that nested invocations of `listOf` (as performed by `[[[[[Int]]]]]`) cause an exponential explosion. What is difficult is to find a solution that doesn't cause *other* kinds of problems.

Consider `(,) <$> arbitrary <*> arbitrary :: Gen ((), [Int])`, which is equivalent to `(,) <$> pure () <*> arbitrary` (by definition of `arbitrary :: Gen ()`), and thus to `(,) () <$> arbitrary` (by monad laws), so the size would not be updated when we generate the second component here.

Similarly, consider this equation, also derived from monad/applicative laws (the point is that `(<*>)` is associative, intuitively, "`(a <*> b) <*> c = a <*> (b <*> c)`"):

    (,,) <$> arbitrary <*> arbitrary <*> arbitrary = (\a (b, c) -> (a,b,c)) <$> arbitrary <*> ((,) <$> arbitrary <*> arbitrary)

if `(<*>)` simply split the size by two, we would get different size distributions on both sides: (1/4, 1/4, 1/2) or (1/2, 1/4, 1/4).

Note that we could disregard that problem with laws by considering a coarser form of program equivalence. Besides, there are other aspects in which things could be made worse by such an approach.

- The size now decreases exponentially in the "depth" of generation: while some generators produce more reasonable values, others may only generate extremely small values. In `genList` below, assuming we somehow default on `[]` once size reaches 0, dividing the size by 2 for every `(<*>)` would only make this generate lists of length `O(log(size))`:

        genList :: Gen [Int]
        genList = oneof [return [], (:) <$> arbitrary <*> genList]


- In fact, what do we do once the size reaches 0? Having to always annotate all choices with a "base case" seems cumbersome. Could we still write an arbitrary instance for `Either`, which has no obvious base case?

I think a stronger case needs to be made here to get something into QuickCheck. You say there is something "dangerous" about the current approach, but how much is really at stake, given that QuickCheck is a testing library? Here's another perspective on this trade-off: nontermination or running out of memory loudly signals that something needs to be fixed, whereas it can be much less clear how to tell that a property is being insufficiently tested because its inputs are all too small (they may still not necessarily be trivial enough that a naive collision-based heuristic would detect it).

Still it would certainly be interesting to actually experiment with a framework where the size parameter has a closer correspondence with a physical notion of size. At least, keeping things simple means that it would be straightforward to build something on top of QuickCheck to work around immediate limitations.

**Comment by NorfairKing** [comment]
@Lysxia Thank you very much for the in-depth explanation. It looks like there are certainly trade-offs to be made here.

Your explanation has certainly gotten halfway to entirely changing my mind. (This is great.)
I will close this issue for now, and experiment in a seperate library before (if ever) I make my case again.

P.S. For the record, I don't recommend dividing the size by two for every split. We would want to choose an arbitrary partition of the size instead.
