### ISSUE TITLE
Poor performance with certain data types, maybe bad Arbitrary instance(s)

### ISSUE THREAD

**Issue by recursion-ninja** [nick8325/quickcheck#210]
I encountered one of my test cases failing to terminate in my [`bv-little`](https://github.com/recursion-ninja/bv-little) project. It appeared to have something to do with the `Arbitrary` instance for `Word` behaving poorly. I've had this happen before in other projects but I circumvented the issue with:

    toEnum . getNonNegative <$> (arbitrary :: NonNegative Int)

This seems unsatisfactory compared to the much simpler `arbitrary :: Word`. All the data types should have well performing `Arbitrary` instances.

I tried my best to isolate the defect with a minimal working example in this repository:

[`bv-little-qc-defect`](https://github.com/recursion-ninja/bv-little-qc-defect)

The test suites `test-integer` and `test-word` perform extremely poorly while `test-double` and `test-int` perform as expected. It seems to have something to do with the strictness of the `ExampleType` located in `Data.ExampleType`.

**Comment by Lysxia** [comment]
The problem is that the function being tested, `problemFunction w = 2 ^ w`, has complexity at least `w^1.5` ([the fast exponentiation by `w` takes approximately proportional time to a multiplication of numbers of size `w`](https://en.wikipedia.org/wiki/Exponentiation_by_squaring#Computational_complexity), and [the best algorithms for that are around `w^1.5`](https://en.wikipedia.org/wiki/Multiplication_algorithm#Fast_multiplication_algorithms_for_large_inputs)), so it is not feasible when `w` is on the order of billions. While the `Double` and `Int` tests apply that function to words in a small range (`[0, 100]`), the problematic ones don't:

- `Arbitrary Integer` may generate negative values of small magnitude, and applying `toInteger` to such a negative value `-i` results in a large `Word` (`maxBound + 1 - i`) (the `Double` and `Int` tests have an `abs` to avoid that case)

- `Arbitrary Word` generates values that grow exponentially in the size parameter (i.e., the size is bounding the number of bits)

**Comment by nick8325** [comment]
Right, the problem is that `Arbitrary Word` generates test data in the full range of a `Word`, which can be any number up to 2^32 or 2^64 (depending on your machine).

To tell QuickCheck to only generate small `Word`s, you can use the [`Small` modifier](https://hackage.haskell.org/package/QuickCheck-2.11.3/docs/Test-QuickCheck-Modifiers.html#t:Small):

```haskell
prop_whatever :: Small Word -> Bool
prop_whatever (Small x) = {- some property about x goes here -}
```

The generator for `Int` is a special case in that it only generates small values; see #182. All the other bounded integral types generate values in their full range.

**Comment by recursion-ninja** [comment]
In our codebase we use `Word` in place of `Int` in instances where the range of values cannot be negative. This includes places where "idiomatic" Haskell code would use an `Int` typed value, despite the value range being strictly non-negative. Some examples are monotonically non-decreasing accumulations, indexing data structures which are isomophic to a list, exponentiation of integral types, etc.

In all other languages I have worked in, there has been no difference between the treatment of the signed and unsigned versions of the architecture-specific, fixed-width integral type. Consequently, I find QuickCheck's functionality a surprising deviation. I would expect the `Arbitrary` instances of `Word` & `Int` to either *both* generate the smaller range or *both* generate the full range. It strikes me as an inconsistent API that violates [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). You mentioned that ["It's intended but not thought through very carefully."](https://github.com/nick8325/quickcheck/issues/182#issuecomment-355359208). Might I suggest that `Word` and `Int` both generate the smaller value range for consistence or both generate the full range of values?

**Comment by recursion-ninja** [comment]
@Lysxia, thank you for pointing out the underlying efficiency issue in the function definition.

I should make the following definitional change in the code that initially raised the issue:

problemFunction = w = 2 ^ w -- Performs poorly on large values of w
problemFunction = w = 1 `shiftR` fromEnum w -- Performs fine, exception if w > (maxBound :: Int)

**Comment by nick8325** [comment]
Yes, I buy that. I'll change the generator for `Word` to match `Int`.
