### ISSUE TITLE
Test.QuickCheck.Test is not being exposed

### ISSUE THREAD

**Issue by tomjaguarpaw** [nick8325/quickcheck#220]
I'm really confused why `Test.QuickCheck.Test` is not being exposed

https://hackage.haskell.org/package/QuickCheck-2.12.4

despite being in `Exposed-Modules`

https://github.com/nick8325/quickcheck/blob/master/QuickCheck.cabal#L76

Do you know why?  I want to use `isSuccess` but it is not exported!

**Comment by tomjaguarpaw** [comment]
Ah OK, well I changed the title of the issue then.  Why is this hidden from Haddock?  `isSuccess` used to be in the docs and now is not.  It seems like the kind of thing you'd want users to have easy access to!

**Comment by tomjaguarpaw** [comment]
This seems to be the commit which effected the change: 80bdfaae6dea8bb73b1eaa10b6e463a3f964ac3b

Was hiding `isSuccess` (and presumably all the other identifiers defined in there) from the docs really the intention of this change?

**Comment by nick8325** [comment]
I'll make it so that `Test.QuickCheck` re-exports `isSuccess` - I'm not sure why it doesn't at the moment.

The idea of that commit was to make the module list on Haddock less confusing by not showing links to the various internal QuickCheck modules. All the user-facing functionality of `Test.QuickCheck.Test` is (or should be) re-exported by `Test.QuickCheck`, so it doesn't need to be imported directly (unless you are doing something very specific such as extending QuickCheck).

**Comment by robx** [comment]
Just to note that the non-generated Haddock for these semi-internal modules just sent me on a rather longer-than-necessary search while trying to understand `hspec`'s quickcheck bindings, which call out to `ioRose`. Due to the missing haddocks, `ioRose` and friends don't show up in either the hackage "Index" page, nor on hoogle.

I appreciate that changing to something friendlier such as a documented `Test.QuickCheck.Internal.*` namespace might not be worth the pain at this point...
