### ISSUE TITLE
Existential Quantifcation

### ISSUE THREAD

**Issue by Ericson2314** [nick8325/quickcheck#24]
It would be nice to be able to use existential quantification in QuickCheck.

Since `∃x(φ(x))` is equivalent to  `¬∀x(¬φ(x))`, the easiest thing to do would be add an `invert :: Testable prop => prop -> Property` "Property Combinator".

**Comment by phadej** [comment]
The problem is that QuickCheck only pretends to do universal quantification, it's very luckily it will fail to find the witness of existential. E.g. with poor generator:

```
∃ x : Int, x > 1000 ≡
¬ ∀ x : Int, x <= 1000
```

Yet

```hs
> quickCheck (\ x -> x <= (1000 :: Int))
+++ OK, passed 100 tests.
```

You can "fix" it, by providing better generator
```hs
λ Prelude Test.QuickCheck > quickCheck (\ x -> x <= (1000 :: Large Int))
*** Failed! Falsifiable (after 20 tests and 4 shrinks):     
Large {getLarge = 1001}
```

---

Yet the best way, is to "prove" the existential by hand and construct it manually.

```
∀ x : Int, ∃ y : Int, such that y > x
Proof:
take y = x + 1
```

```hs
 > quickCheck (\x -> x < x + (1 :: Int))
+++ OK, passed 100 tests.
```

**Comment by nick8325** [comment]
Closed because as @phadej noted there's no real way to support existential quantification in QuickCheck.

**Comment by Ericson2314** [comment]
Well. the likeliness of failing to find the witness depends on the prop. My intent was more to use this for manual searches on the repl than use it in testsuites.

**Comment by nick8325** [comment]
Well, the problem is more that quantifier _alternation_ is impossible to support efficiently in QuickCheck. For example, testing ∀ x ∃ y ..., you have to generate 100 values of x, and for each value of x you may have to try 100 values of y to find the witness. The number of tests executed will be exponential in the number of quantifier alternations. And when a test fails there is no real counterexample we can give.

If you have only existential quantification and no universal quantification, you can use `expectFailure`, which effectively negates a property (but always adds the negation at the very top of the property). But this only changes the message QuickCheck prints when it finds a witness/counterexample - it's probably not useful at the REPL.

**Comment by Ericson2314** [comment]
I'm a bit rusty on the details, but I think my usecase was trying to find a ~7 gate circuit to match a little truth table. This would be `∃ circuit ∀ input-values ...`.

**Comment by phadej** [comment]
@Ericson2314 try [`smallcheck`](http://hackage.haskell.org/package/smallcheck-1.1.1/docs/Test-SmallCheck.html), as it's exhaustive (to some depth), then you'll find a witness, or `smallcheck` will tell that there aren't small one.

**Comment by Ericson2314** [comment]
phadej oh that's perfect---any situation I can expect to find the existential witness, depth-first determinism should not be a problem. Thanks!
