### ISSUE TITLE
Memory explodes using QuickCheck 2.13.1

### ISSUE THREAD

**Issue by asr** [nick8325/quickcheck#253]
I get instantly the following output using QuickCheck 2.12.6.1

``` 
$ ./Test 
=== prop_monoid_MaxNat from Test.hs:60 ===
+++ OK, passed 100 tests.
```

but memory explodes when using QuickCheck 2.13.1.

File: [Test.hs.txt](https://github.com/nick8325/quickcheck/files/3025105/Test.hs.txt)
GHC version: 8.6.4
OS: Ubuntu

Blocking https://github.com/agda/agda/issues/3663.

**Comment by phadej** [comment]
Could you try 2.13?

**Comment by nick8325** [comment]
This is actually a bug in your generator. In the line `NonNegative x <- arbitrary`, the call to `arbitrary` has type `Gen (NonNegative MaxNat)`, so your `Arbitrary` instance ends up recursing into itself!

This didn't blow up in QC 2.12 because the `Arbitrary` instance for `NonNegative a` would sometimes return 0 directly. However, this meant that your generator was only ever producing 0 (try `sample (arbitrary :: Gen MaxNat)` on QC < 2.13).

Here is a correct version:

```
instance Arbitrary MaxNat where
  arbitrary = do
    NonNegative x <- arbitrary
    return (MaxNat x)
```

**Comment by asr** [comment]
Thanks! I pushed the above commit fixing the buggy instances in Agda.
