### ISSUE TITLE
Why does CoArbitrary (a -> b) use map f?

### ISSUE THREAD

**Issue by nh2** [nick8325/quickcheck#38]
Just a question of understanding. We currently have:

```haskell
instance (Arbitrary a, CoArbitrary b) => CoArbitrary (a -> b) where
  coarbitrary f gen =
    do xs <- arbitrary
       coarbitrary (map f xs) gen
```

Why do we do `map f xs` here? Why not simply:

```haskell
instance (Arbitrary a, CoArbitrary b) => CoArbitrary (a -> b) where
  coarbitrary f gen =
    do x <- arbitrary
       coarbitrary (f x) gen
```

Thanks!

**Comment by nick8325** [comment]
Hi,

The `CoArbitrary` instance for function types is used when generating a higher-order function of type `(a -> b) -> c`. What we do is pick a random list of inputs of type `[a]`, then when given a function of type `a -> b` we sample it on those inputs and use the outputs `[b]` to determine the final result `c`.

By replacing `map f xs` with `f x`, we would only sample the function on one input. This means that when generating a random function of type `(a -> b) -> c`, we would pick a single value of type `a`, and the generated function would in effect only apply its argument to that single value.

As a result, the following property would pass although it's false:

```haskell
prop :: Blind ((Bool -> Bool) -> Bool) -> Bool
prop (Blind f) = f (const False) == f id || f (const True) == f id
```

The reason is that the property holds for all functions of type `(Bool -> Bool) -> Bool` that only apply their argument to either `True` or `False` but not both.

**Comment by nh2** [comment]
Thanks for the great explanation!

This is pretty good - maybe it should even be part of the code!
