### ISSUE TITLE
QuickCheck reporting correct examples as failing

### ISSUE THREAD

**Issue by manleyjster** [nick8325/quickcheck#53]
Hi all - 

I'm having trouble with QuickCheck reporting correct examples as failing. I've put together a [minimal example demonstrating this behavior in a Gist](https://gist.github.com/manleyjster/6a728b7fd8945459f4c1). I've trimmed it down and tested it on multiple machines, and I believe by this point that it's a library bug.

The following is copied for your convenience from the README in the Gist:

### QuickCheck Bug?

This repo documents a strange behavior I encountered when trying to test some code using the Data.Graph.Inductive library with QuickCheck.

QuickCheck will report failing examples for the test `mergeWithFixTrue` (see `Test.hs`). However, when these failing examples are copied into unit tests and run using HUnit, they invariably succeed.

This begs the question - why QuickCheck? Might HUnit not as easily be at fault? There are two reasons why I believe QuickCheck might be at fault here:

1. Looking at small failing examples and working the function call out by hand, the failing examples should not be failing.
2. By inserting calls to Debug.Trace.trace, I've been able to tell that **`mergeWith` (see `Merge.hs`) behaves differently when called with `fixBody` from QuickCheck vs. HUnit or `cabal repl`**. When it is called via QuickCheck, `mergeWith fixBody` returns a graph with an extra edge in it, and it is this unwanted edge that causes the test to fail.

### Running

To reproduce the behavior described above, clone this repository and initialize a cabal sandbox with `cabal sandbox init`. Then run the following:

1. cabal install --only-dependencies --enable-tests
2. cabal test

You may have to run `cabal test` a few times to get a failing example from QuickCheck. I like to run `cabal test` until I get a nice, bite-sized failing example (no more than 3 or 4 edges in the example graph).

Once you've done this, insert the failing example into the HUnit test in `Test.hs` on the line starting with: "testCase" (the failing example should go in the let-binding: `let g = <failing example here>`).

Run `cabal test` again, and notice that the example which QuickCheck reports as a failure runs perfectly well in HUnit.

**Comment by nick8325** [comment]
Hi,

The reason the property fails is that the `randomGraph` generator can return edges between nodes which are not in the graph. In your test case, ```Graph.mkGraph [(1,())] [(1,2,False),(1,3,True)]```, the only node is 1 but there are edges to the non-existent nodes 2 and 3.

This is because the line ```lnodes = zip nodes <$> arbitrary``` generates a list of some length and truncates ```lnodes``` to that length. To fix it you can change the line to ```lnodes = zip nodes <$> infiniteList```. After that the property passes.

But why does the counterexample succeed when you run it with HUnit? The answer is that fgl seems to behave eccentrically when there is an edge to a non-existent node, and in particular the `Show` instance for graphs doesn't print out the graph correctly.

Here's what's going on, I think: the actual counterexample has an extra edge ```(2,1, True)```. For whatever reason, because 2 is not in the graph ```mergeWith``` does the wrong thing. Unfortunately, fgl ignores this edge when printing the graph because the source node doesn't exist. As a result, when you print the graph and read it back in you lose this edge and the property passes.

**Comment by manleyjster** [comment]
Thanks for the (amazingly) quick response, Nick!

You were exactly right about the issue having to do with edges between vertices not in the graph. Thanks - I really appreciate it!
