### ISSUE TITLE
Optionally use the old stdgen (instead of tf-random)

### ISSUE THREAD

**Issue by skogsbaer** [nick8325/quickcheck#58]
We have quite a lot of quickcheck properties with replay arguments. The replay arguments are specified with the old StdGen. However, the most recent quickcheck version forces you to use tf-random.

Would it be possible to have a cabal flag specifying that you want to use StdGen? For older versions of ghc and base, you do this anyway.

**Comment by reiddraper** [comment]
Presumably if you're using a new version of QuickCheck, it's not at all guaranteed that an old seed would even mean the same thing, right? More or less entropy might be taken from the RNG, as an implementation-detail.

**Comment by nick8325** [comment]
Yes, @reiddraper is right. You can't reliably replay tests between different QuickCheck versions because the implementation of the generators may have changed. In particular, the `Arbitrary` instance for `Int` changed between 2.6 and 2.7 so any property involving `Int` will replay differently. Replaying is meant more for immediately repeating a test (e.g. after fixing a bug).

I've added a comment which clarifies this - unfortunately the documentation said nothing about it before.

What I would do in your case is get an old version of QuickCheck and turn the replay arguments into actual test cases (e.g. using `verboseCheck`). Then you can test these test cases directly instead of using replay.

**Comment by nick8325** [comment]
Closed because we can't replay tests between QuickCheck versions anyway.
