### ISSUE TITLE
`verboseCheck` for `Fun` resource intensive and remains in background. 

### ISSUE THREAD

**Issue by bradyt** [nick8325/quickcheck#96]
If I run `verboseCheck prop` with `prop` defined below, it slows my computer down and doesn't terminate. If I cancel the running command with `Ctrl+c Ctrl+c`, the command stops and prompt returns, but it seems process is still running and computer is slowed. Until I exit ghci prompt. This problem does not occur for `quickCheck prop`. 

    prop :: Fun String Integer -> Bool
    prop (Fun _ f) = f "monkey" == f "banana" || f "banana" == f "elephant"

**Comment by phadej** [comment]
I guess that printing `Fun` while still generating it, makes a loop.

**Comment by phadej** [comment]
Especially a `:->` which uses `Table` constructor, as simple `ADT` like `Bool` works fine:

```hs
let { prop :: Fun Bool Int -> Bool; prop (Fun _ f) = f False == f True } in verboseCheck prop
Passed:  
{False->0, True->0, _->0}
Failed: 
{False->1, True->-1, _->1}
*** Failed! Passed:                       
{False->1, _->1}
Failed:                                       
{True->-1, _->1}
Passed:                                    
{_->1}
Passed:                                       
{_->1}
Passed:                                       
{True->1, _->1}
Failed:                                       
{True->0, _->1}
Passed:                                     
{_->1}
Passed:                                       
{_->1}
Passed:                                       
{True->0, _->0}
Falsifiable (after 2 tests and 2 shrinks):    
{True->0, _->1}
```

**Comment by nick8325** [comment]
This is unfortunate. `Test.QuickCheck.Function` relies fundamentally on shrinking: it represents a function as an infinite case-split with random values for the leaves, which shrinking reduces to a finite case-split.

So there is no way to show a random function pre-shrinking, because it's infinite. But `verboseCheck` should obviously not crash. I suppose it should print `<fun>` or something along those lines instead - I'll fix it to do that.
